"""add_progress

Revision ID: 1fe246909f03
Revises: 372f57f974fb
Create Date: 2026-04-09 17:34:08.912279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe246909f03'
down_revision: Union[str, None] = '372f57f974fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('documents', sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
