"""Update to Many-to-Many documents

Revision ID: 372f57f974fb
Revises: 1f70593de158
Create Date: 2026-04-06 16:16:06.426742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372f57f974fb'
down_revision: Union[str, None] = '1f70593de158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_documents',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'document_id')
    )
    op.drop_constraint('documents_workspace_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key('documents_workspace_id_fkey', 'documents', 'workspaces', ['workspace_id'], ['id'])
    op.drop_table('workspace_documents')
    # ### end Alembic commands ###
